FROM nginx:1.21-alpine

RUN curl -sSL "https://github.com/h5bp/server-configs-nginx/archive/3.3.0.tar.gz" | tar -xzf - --strip-components=1 -C /etc/nginx && \
    sed -i -r 's/user www-data/user nginx/' /etc/nginx/nginx.conf && \
    rm -rf /etc/nginx/conf.d/*

EXPOSE 5000

COPY /container_root /
