version: '3'
services:
  generator:
    build: .
    image: dofus-almanax:0.1
    volumes:
      - almanax_public:/opt/almanax/public:rw
      - almanax_data:/opt/almanax/dl:rw
  web:
    image: caddy:2-alpine
    restart: always
    depends_on:
      - generator
    volumes:
      - almanax_public:/usr/share/caddy:ro
      - ${PWD}/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 8888:80
  cron:
    image: dofus-almanax:0.1
    restart: always
    entrypoint: /usr/sbin/crond
    command: ["-f", "-l", "8"]
    volumes:
      - almanax_public:/opt/almanax/public:rw
      - almanax_data:/opt/almanax/dl:rw
      - ./cron_scripts:/etc/periodic/daily:ro

volumes:
  almanax_public:
  almanax_data:
