version: '3'
services:
  generator:
    build: .
    image: dofus-almanax
    volumes:
      - almanax_public:/opt/almanax/public:rw
      - almanax_data:/opt/almanax/dl:rw
  web:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: dofus-almanax-web
    depends_on:
      - generator
    volumes:
      - almanax_public:/var/www/html:ro
    ports:
      - 5000
  cron:
    image: dofus-almanax
    entrypoint: /usr/sbin/crond
    command: ["-f"]
    volumes:
      - almanax_public:/opt/almanax/public:rw
      - almanax_data:/opt/almanax/dl:rw
      - ./cron_scripts:/etc/periodic/daily:ro

volumes:
  almanax_public:
  almanax_data:
